Repository binbashar/le-tf-infra-aws, pull requests merged in 2022-08, with the labels that each got.

#418 Enhancement | wafv2 fix rules and add outputs
  apps-devstg/us-east-1/security-firewall --/outputs.tf
  apps-devstg/us-east-1/security-firewall --/wafv2-regional.tf
Labels: enhancement, patch

#420 Enhancement | Shared/ container-registry bump modules version
  shared/us-east-1/container-registry/.terraform.lock.hcl
  shared/us-east-1/container-registry/config.tf
  shared/us-east-1/container-registry/ecr_repositories.tf
  shared/us-east-1/container-registry/lifecycle_policy.tf
  shared/us-east-2/container-registry/.terraform.lock.hcl
  shared/us-east-2/container-registry/config.tf
  shared/us-east-2/container-registry/ecr_repositories.tf
  shared/us-east-2/container-registry/lifecycle_policy.tf
Labels: enhancement, patch

#423 Fix | /shared/us-east-2/container-registry
  shared/us-east-2/container-registry/config.tf
Labels: patch, fix

#419 Enhancement | Management admins
  .gitignore
  apps-devstg/global/base-identities/.terraform.lock.hcl
  apps-devstg/global/base-identities/roles.tf
  apps-prd/global/base-identities/.terraform.lock.hcl
  apps-prd/global/base-identities/keys/machine.auditor.ci
  apps-prd/global/base-identities/roles.tf
  management/global/base-identities/.terraform.lock.hcl
  management/global/base-identities/roles.tf
  network/global/base-identities/.terraform.lock.hcl
  network/global/base-identities/roles.tf
  security/global/base-identities/groups.tf
  security/global/base-identities/roles.tf
  shared/global/base-identities/.terraform.lock.hcl
  shared/global/base-identities/keys/machine.auditor.ci
  shared/global/base-identities/roles.tf
Labels: enhancement, minor

#424 Feature | apps-devstg/databases-aurora/ Update versions constraint + Update modules version
  apps-devstg/us-east-1/databases-aurora/.terraform.lock.hcl
  apps-devstg/us-east-1/databases-aurora/cluster_demoapps.tf
  apps-devstg/us-east-1/databases-aurora/config.tf
  apps-devstg/us-east-1/databases-aurora/outputs.tf
Labels: feature, patch

#425 Enhancement | Update AWS Required Providers & Update WAFv2 Module Version
  apps-devstg/us-east-1/security-firewall --/config.tf
  apps-devstg/us-east-1/security-firewall --/wafv2-regional.tf
Labels: enhancement, minor

#426 Enhancement | implementing aws inspector2
  config/common-variables.tf
  management/global/organizations/.terraform.lock.hcl
  management/global/organizations/config.tf
  management/global/organizations/organization.tf
  management/global/sso/.terraform.lock.hcl
  management/global/sso/policies.tf
  management/us-east-1/security-compliance/.terraform.lock.hcl
  management/us-east-1/security-compliance/awsinspector_delegation.tf
  management/us-east-1/security-compliance/variables.tf
  security/us-east-1/security-compliance --/.terraform.lock.hcl
  security/us-east-1/security-compliance --/README.md
  security/us-east-1/security-compliance --/awsconfig.tf
  security/us-east-1/security-compliance --/awsinspector.tf
  security/us-east-1/security-compliance --/locals.tf
  security/us-east-1/security-compliance --/outputs.tf
  security/us-east-1/security-compliance --/variables.tf
Labels: feature, minor

#427 Feature | Workflow and layer to test CLI
  .github/workflows/leverage-cli-test.yml
  apps-devstg/global/cli-test-layer/.terraform.lock.hcl
  apps-devstg/global/cli-test-layer/common-variables.tf
  apps-devstg/global/cli-test-layer/config.tf
  apps-devstg/global/cli-test-layer/locals.tf
  apps-devstg/global/cli-test-layer/policies.tf
  apps-devstg/global/cli-test-layer/roles.tf
Labels: feature, minor

#429 Doc | README.md-update-banner
  README.md
Labels: patch, documentation
