Repository binbashar/le-tf-infra-aws, pull requests merged in 2022-10, with the labels that each got.

#416 Feature | Implement external-secrets for Apps-DevStg K8s-EKS cluster
  apps-devstg/us-east-1/k8s-eks/README.md
  apps-devstg/us-east-1/k8s-eks/identities/config.tf
  apps-devstg/us-east-1/k8s-eks/identities/ids_aws_lb_controller.tf
  apps-devstg/us-east-1/k8s-eks/identities/ids_certmanager.tf
  apps-devstg/us-east-1/k8s-eks/identities/ids_cluster_autoscaler.tf
  apps-devstg/us-east-1/k8s-eks/identities/ids_external_secrets.tf
  apps-devstg/us-east-1/k8s-eks/identities/ids_externaldns_aws.binbash.com.ar.tf
  apps-devstg/us-east-1/k8s-eks/identities/locals.tf
  apps-devstg/us-east-1/k8s-eks/identities/outputs.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/external-secrets.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/namespaces.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/networking-ingress.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/security.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks/k8s-components/variables.tf
  apps-devstg/us-east-1/k8s-eks/network/config.tf
Labels: feature, patch

#441 Fix the 'ConsoleSignInWithoutMfaCount' alarm when users access via SSO
  security/us-east-1/security-audit/metrics.auto.tfvars
Labels: patch, fix

#438 GitHub Actions OIDC integration and more
  shared/global/base-identities/identity_providers.tf
  shared/global/base-identities/locals.tf
  shared/global/base-identities/policies.tf
  shared/global/base-identities/roles.tf
  shared/us-east-1/container-registry/locals.tf
Labels: feature, minor
