Repository binbashar/le-tf-infra-aws, pull requests merged in 2022-07, with the labels that each got.

#401 Enhancement | Add enable ssm access variable
  shared/us-east-1/tools-vpn-server/.terraform.lock.hcl
  shared/us-east-1/tools-vpn-server/config.tf
  shared/us-east-1/tools-vpn-server/ec2.tf
  shared/us-east-1/tools-vpn-server/locals.tf
  shared/us-east-1/tools-vpn-server/variables.tf
Labels: feature, patch

#403 Doc | apps-devstg-k8s-eks layer README.md improvement
  apps-devstg/us-east-1/k8s-eks/README.md
Labels: patch, documentation

#404 apps-devstg/us-east-1/k8s-eks-v1.17 adjustments
  apps-devstg/us-east-1/k8s-eks-v1.17/k8s-resources/apps.auto.tfvars
  apps-devstg/us-east-1/k8s-eks-v1.17/k8s-resources/variables.tf
Labels: patch, fix

#405 Feature | terraform aws apps-devstg/us-east-1/k8s-eks/k8s-components and k8s-workloads layers
  apps-devstg/us-east-1/k8s-eks/README.md
  apps-devstg/us-east-1/k8s-eks/cluster/outputs.tf
  apps-devstg/us-east-1/k8s-eks/identities/ids_cluster_autoscaler.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/.terraform.lock.hcl
  apps-devstg/us-east-1/k8s-eks/k8s-components/backup.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/alb-ingress.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/argo-cd.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/certmanager.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/cluster-autoscaler.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/clusterissuer-binbash.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/externaldns.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/fluentbit.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/fluentd-daemonset.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/fluentd-elasticsearch-aws.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/fluentd-elasticsearch-selfhosted.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/gatus.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/goldilocks.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/ingress-monitor-controller-endpoint.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/ingress-monitor-controller-ingress-endpoint.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/ingress-monitor-controller.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/ingress-nginx.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/kube-state-metrics.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/kubernetes-dashboard.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/metrics-server.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/node-exporter.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/vault.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/velero.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/vpa.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/cicd-argo.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/common-variables.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/config.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/identity-external-prometheus.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/identity-grafana-kubegraf.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/ingress-monitor-controller.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/locals.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/monitoring-logging.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/monitoring-metrics.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/monitoring-tools.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/namespaces.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/networking-dns.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/networking-ingress.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/scaling.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/security.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks/k8s-components/variables.tf
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/.terraform.lock.hcl
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/chart-values/demoapps-emojivoto.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/chart-values/demoapps-gmd.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/chart-values/demoapps-sockshop.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/common-variables.tf
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/config.tf
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/demoapps.tf
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/variables.tf
  shared/global/base-dns/binbash.com.ar/config.tf
  shared/global/base-dns/binbash.com.ar/outputs.tf
  shared/global/base-dns/binbash.com.ar/zone_private.aws.binbash.com.ar.tf
Labels: feature, minor

#406 Fix | global config variables fixed
  apps-devstg/us-east-1/k8s-eks/k8s-components/monitoring-logging.tf
  apps-devstg/us-east-1/k8s-eks/k8s-workloads/demoapps.tf
Labels: patch, fix

#408 Feature | cdn-s3-frontend/ Update versions constraint + Update modules versions
  apps-devstg/us-east-1/cdn-s3-frontend --/.terraform.lock.hcl
  apps-devstg/us-east-1/cdn-s3-frontend --/config.tf
  apps-devstg/us-east-1/cdn-s3-frontend --/dev.aws.binbash.com.ar.tf
  apps-prd/us-east-1/cdn-s3-frontend --/.terraform.lock.hcl
  apps-prd/us-east-1/cdn-s3-frontend --/config.tf
  apps-prd/us-east-1/cdn-s3-frontend --/www.binbash.com.ar.tf
Labels: feature, patch

#415 Enhancement | Add networkmanager / firewall permissions to DevOps IAM Policy
  management/global/sso/policies.tf
Labels: enhancement, minor

#417 Fix | Feature/prune configuration and files
  @bin/scripts/validate-terraform-layout.sh
  apps-devstg/global/base-identities/roles.tf
  apps-prd/global/base-identities/roles.tf
  build.py
  config/common.tfvars.example
  management/global/base-identities/roles.tf
  management/global/cost-mgmt/main.tf
  management/global/sso/account_assignments.tf
  management/us-east-1/notifications/costs_tools_monitoring.tf
  management/us-east-1/notifications/policies.tf
  management/us-east-1/security-audit/awscloudtrail.tf
  management/us-east-1/security-keys/kms.tf
  security/global/base-identities/roles.tf
  security/us-east-1/security-compliance --/awsconfig.tf
  security/us-east-1/security-keys/kms.tf
  security/us-east-1/security-monitoring/guardduty.tf
  security/us-east-2/security-monitoring --/guardduty.tf
  shared/global/base-identities/roles.tf
  shared/us-east-1/secrets-manager --/secrets.tf
Labels: patch, fix
