Repository binbashar/le-tf-infra-aws, pull requests merged in 2022-06, with the labels that each got.

#390 Feature / Update Backups Layers with tf providers latest versions
  apps-devstg/us-east-1/backups --/.terraform.lock.hcl
  apps-devstg/us-east-1/backups --/config.tf
  apps-devstg/us-east-1/backups --/main.tf
  apps-devstg/us-east-1/backups --/variables.tf
  apps-prd/us-east-1/backups --/.terraform.lock.hcl
  apps-prd/us-east-1/backups --/config.tf
  apps-prd/us-east-1/backups --/main.tf
  apps-prd/us-east-1/backups --/variables.tf
Labels: feature, patch

#391 Added DNS records for sendgrid validation
  shared/global/base-dns/binbash.com.ar/zone_public.binbash.com.ar.tf
Labels: feature, patch

#393 Bug | updating module version + terraform aws provider constraint
  shared/us-east-1/tools-vpn-server/.terraform.lock.hcl
  shared/us-east-1/tools-vpn-server/config.tf
  shared/us-east-1/tools-vpn-server/ec2.tf
Labels: bug, patch

#394 Feature/ shared/backups update tf providers versions
  shared/us-east-1/backups/.terraform.lock.hcl
  shared/us-east-1/backups/config.tf
  shared/us-east-1/backups/variables.tf
Labels: feature, patch

#395 updated external-dns bitnami chart version
  apps-devstg/us-east-1/k8s-eks/k8s-resources/networking.tf
Labels: minor, fix

#396 Feature | ec2-fleet/ Update versions constraint + Update modules versions + Enable SSM service
  apps-devstg/us-east-1/ec2-fleet-ansible --/.terraform.lock.hcl
  apps-devstg/us-east-1/ec2-fleet-ansible --/config.tf
  apps-devstg/us-east-1/ec2-fleet-ansible --/ec2_fleet.tf
  apps-devstg/us-east-1/ec2-fleet-ansible --/locals.tf
  apps-devstg/us-east-1/ec2-fleet-ansible --/outputs.tf
  apps-devstg/us-east-1/ec2-fleet-ansible --/security.tf
  apps-devstg/us-east-1/ec2-fleet-ansible --/variables.tf
  apps-prd/us-east-1/ec2-fleet --/.terraform.lock.hcl
  apps-prd/us-east-1/ec2-fleet --/config.tf
  apps-prd/us-east-1/ec2-fleet --/ec2_fleet.tf
  apps-prd/us-east-1/ec2-fleet --/locals.tf
  apps-prd/us-east-1/ec2-fleet --/outputs.tf
  apps-prd/us-east-1/ec2-fleet --/security.tf
  apps-prd/us-east-1/ec2-fleet --/variables.tf
  shared/us-east-1/ec2-fleet --/.terraform.lock.hcl
  shared/us-east-1/ec2-fleet --/config.tf
  shared/us-east-1/ec2-fleet --/ec2_fleet.tf
  shared/us-east-1/ec2-fleet --/locals.tf
  shared/us-east-1/ec2-fleet --/outputs.tf
  shared/us-east-1/ec2-fleet --/security.tf
  shared/us-east-1/ec2-fleet --/variables.tf
Labels: feature, patch
