Repository binbashar/le-tf-infra-aws, pull requests merged in 2022-03, with the labels that each got.

#360 Fix demoapps layers
  apps-devstg/us-east-1/base-network/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/eks-workers-managed.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/identity_providers.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/policies.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/roles.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/chart-values/certmanager.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/chart-values/externaldns-private.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/chart-values/externaldns-public.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/ci_cd.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/demoapps.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/monitoring_tools.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/namespaces.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/networking.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/scaling.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/security.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-resources/variables.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/network.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/variables.tf
  apps-devstg/us-east-1/k8s-eks/k8s-resources/chart-values/demoapps-emojivoto.yaml
  apps-devstg/us-east-1/k8s-eks/network/network.tf
  security/global/base-identities/role_policies.tf
Labels: patch, fix

#362 Disable SSM endpoints in apps-prd
  apps-prd/us-east-1/base-network/network.auto.tfvars
Labels: patch, fix

#365 Bugfix | Change pre-commit hooks url's protocol to https
  .pre-commit-config.yaml
Labels: minor, fix

#359 Feature / Update bb_mysql_db to use the latest version of tf_aws_rds module
  apps-devstg/us-east-1/databases-mysql --/.terraform.lock.hcl
  apps-devstg/us-east-1/databases-mysql --/config.tf
  apps-devstg/us-east-1/databases-mysql --/db_mysql.tf
  apps-devstg/us-east-1/databases-mysql --/variables.tf
Labels: feature, patch

#366 Feature/code clean up
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .gitignore
  @bin/scripts/aws_credentials_setup/aws_setup_credentials.py
  @bin/scripts/aws_credentials_setup/requirements.txt
  _lib/terraform.py
  build.py
  config/common.tfvars.example
  shared/us-east-1/tools-vpn-server/.terraform.lock.hcl
Labels: feature, patch
