Repository binbashar/le-tf-infra-aws, pull requests merged in 2023-01, with the labels that each got.

#455 Enhancement | Admin Group policies on Management Account
  management/global/base-identities/.terraform.lock.hcl
  management/global/base-identities/groups.tf
  management/global/base-identities/groups_policies.tf
Labels: minor, fix

#456 Fix | ConsoleSignInWithoutMfaCount false positive on Management Account
  management/us-east-1/security-audit/metrics.auto.tfvars
Labels: patch, fix

#458 ISSUE-152 Refactored RefArch-CLI-Toolbox test
  .github/workflows/leverage-cli-test.yml
Labels: enhancement, patch

#461 ISSUE-460 Toolbox version fixed
  build.env
Labels: enhancement, patch

#447 Doc | improve tools vpn server inline comments + aws-organization README.md added
  management/global/organizations/aws-tf-organization.md
  shared/us-east-1/tools-vpn-server/.terraform.lock.hcl
  shared/us-east-1/tools-vpn-server/ec2.tf
Labels: patch, documentation

#462 Add Kube Prometheus Stack to the DemoApps
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/eks-workers-managed.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/kube-prometheus-stack.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/monitoring-metrics.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/namespaces.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/variables.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/config.tf
  management/global/sso/policies.tf
Labels: feature, minor

#464 Self-Hosted runner module updated
  shared/us-east-1/tools-github-selfhosted-runners/MODULE_MIGRATION_NOTES_0.13.1_to_1.18.2.md
  shared/us-east-1/tools-github-selfhosted-runners/config.tf
  shared/us-east-1/tools-github-selfhosted-runners/lambdas-download/main.tf
  shared/us-east-1/tools-github-selfhosted-runners/main.tf
  shared/us-east-1/tools-github-selfhosted-runners/templates/user-data.sh
Labels: enhancement, patch
