Repository binbashar/le-tf-infra-aws, pull requests merged in 2023-03, with the labels that each got.

#475 Enhacement | base-dns: Update versions constraint
  shared/global/base-dns/binbash.com.ar/.terraform.lock.hcl
  shared/global/base-dns/binbash.com.ar/config.tf
Labels: enhancement, patch

#481 Migrate from JumpCloud to AWS IAM Identity Center (SSO)
  management/global/sso/.terraform.lock.hcl
  management/global/sso/account_assignments.tf
  management/global/sso/config.tf
  management/global/sso/locals.tf
  management/global/sso/permission_sets.tf
  management/global/sso/policies.tf
  management/global/sso/users_groups.tf
  management/global/sso/variables.tf
Labels: feature, minor

#490 Add SSO DevOps role as an admin of the DemoApps cluster
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/locals.tf
Labels: feature, patch

#484 477 | Enable ALB access logs for EKS clusters
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/networking-ingress.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/variables.tf
  apps-devstg/us-east-1/k8s-eks/cluster/config.tf
  apps-devstg/us-east-1/k8s-eks/identities/ids_external_secrets.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/locals.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/networking-ingress.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/variables.tf
  apps-devstg/us-east-1/security-audit/logs.tf
  apps-devstg/us-east-1/security-audit/variables.tf
  apps-devstg/us-east-1/security-certs/outputs.tf
Labels: feature, patch

#496 LEWW-93 | shared-base-dns: create dns record for google search console
  shared/global/base-dns/binbash.com.ar/.terraform.lock.hcl
  shared/global/base-dns/binbash.com.ar/zone_public.binbash.com.ar.tf
Labels: feature
