Repository binbashar/le-tf-infra-aws, pull requests merged in 2023-04, with the labels that each got.

#502 Feature | adding martin.galeano user via AWS IdC (sso)
  .circleci/config.yml
  build.env
  management/global/sso/locals.tf
Labels: feature

#505 Fix/readme.md links
  README.md
Labels: patch, fix

#503 Issue 500 feature add reference secret manager implementation demoapps
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/ids_external_secrets.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/.terraform.lock.hcl
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/security.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks-demoapps/secrets/common-variables.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/secrets/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/secrets/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/secrets/outputs.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/secrets/secrets.tf
Labels: feature, patch
