Repository binbashar/le-tf-infra-aws, pull requests merged in 2023-02, with the labels that each got.

#467 Doc | mananagement aws organizations layer README.md merge
  management/global/organizations/README.md
  management/global/organizations/aws-tf-organization.md
Labels: patch, documentation

#469 Update build.env
  build.env
Labels: enhancement, patch

#470 Issue 3 fitting demoapps needs
  .gitignore
  apps-devstg/global/base-identities/policies.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/NOTES.md
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/eks-workers-managed.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/variables.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/networking-dns.tf
  shared/global/base-identities/policies.tf
Labels: enhancement, patch

#471 Update build.env
  build.env
Labels: enhancement, patch

#472 Chore: Update ArgoCD deployment definition to allow Web Terminal in UI
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/argo-cd.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/argo-rollouts.yaml
  apps-devstg/us-east-1/k8s-eks/k8s-components/cicd-argo.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/namespaces.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/security.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks/k8s-components/variables.tf
Labels: enhancement, patch

#473 Enhacement | container-registry : Update versions constraint
  shared/us-east-1/container-registry/.terraform.lock.hcl
  shared/us-east-1/container-registry/config.tf
  shared/us-east-2/container-registry/.terraform.lock.hcl
  shared/us-east-2/container-registry/config.tf
Labels: enhancement, patch

#478 Enhancement | Implement VPC Flow logs on EKS VPCs
  apps-devstg/us-east-1/base-network/network_vpc_flow_logs.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/network.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/variables.tf
  apps-devstg/us-east-1/k8s-eks/network/network.tf
  apps-devstg/us-east-1/k8s-eks/network/variables.tf
  apps-prd/us-east-1/base-network/network_vpc_flow_logs.tf
  shared/us-east-1/base-network/vpc_flow_logs.tf
  shared/us-east-2/base-network/vpc_flow_logs.tf
Labels: feature
