Repository binbashar/le-tf-infra-aws, pull requests merged in 2024-11, with the labels that each got.

#650 Security | mgmt/global/sso permission updates
  build.env
  management/global/sso/locals.tf
  management/global/sso/policies.tf
Labels: security, patch

#651 Update Pritunl to run on Ubuntu 23
  shared/us-east-1/tools-vpn-server/.terraform.lock.hcl
  shared/us-east-1/tools-vpn-server/config.tf
  shared/us-east-1/tools-vpn-server/ec2.tf
  shared/us-east-1/tools-vpn-server/variables.tf
Labels: enhancement, patch

#656 Security / onboarding new devops user
  management/global/sso/locals.tf
  management/global/sso/policies.tf
Labels: security, patch

#657 Security | adding new devops user
  management/global/sso/locals.tf
Labels: security, patch

#654 Added KEDA and KEDA-HTTP-Addon to k8s-components
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/namespaces.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/scaling.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/variables.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/namespaces.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/scaling.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks/k8s-components/variables.tf
Labels: feature, patch

#658 Create genAI infra for the demo
  data-science/us-east-1/genai-llm-rag-bedrock-poc/README.md
  data-science/us-east-1/genai-llm-rag-bedrock-poc/assets/images/genai-llm-rag-bedrock-poc.png
  data-science/us-east-1/genai-llm-rag-bedrock-poc/ecr.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc/github_workflow.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc/locals.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc/secret.tf
Labels: enhancement, patch

#652 Feature | Deploy emojivoto in devstg cluster
  apps-devstg/us-east-1/k8s-eks-demoapps/addons/addons.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/addons/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/addons/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/.terraform.lock.hcl
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/eks-workers-managed.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/variables.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/argo-cd.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/argocd-image-updater.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/cicd-argo.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-workloads/emojivoto.tf
  shared/global/base-identities/policies.tf
  shared/global/base-identities/roles.tf
  shared/us-east-1/container-registry/.terraform.lock.hcl
  shared/us-east-1/container-registry/locals.tf
  shared/us-east-1/secrets-manager/secrets.tf
Labels: feature, minor

#660 Feature/datalake demo
  data-science/us-east-1/databases-aurora-mysql--/database_resources.tf
  data-science/us-east-1/datalake-demo--/config.tf
  data-science/us-east-1/datalake-demo--/config/table_mappings.json
  data-science/us-east-1/datalake-demo--/config/task_settings.json
  data-science/us-east-1/datalake-demo--/dms.tf
  data-science/us-east-1/datalake-demo--/locals.tf
  data-science/us-east-1/datalake-demo--/outputs.tf
  data-science/us-east-1/datalake-demo--/s3.tf
  management/global/sso/policies.tf
  shared/us-east-1/base-network/config.tf
  shared/us-east-1/base-network/locals.tf
  shared/us-east-1/base-network/vpc_peerings.tf
Labels: enhancement, patch
