Repository binbashar/le-tf-infra-aws, pull requests merged in 2024-07, with the labels that each got.

#601 Increase billing and budget alert threshold to accommodate to the fix…
  management/global/cost-mgmt/variables.tf
Labels: enhancement, patch

#600 FEATURE/ added new KOPS K8s layer
  apps-devstg/us-east-1/k8s-kops/.gitignore
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/config.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/data.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/dns.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/locals.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/outputs.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/s3.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/terraform.auto.tfvars
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/variables.tf
  apps-devstg/us-east-1/k8s-kops/2-kops/.gitignore
  apps-devstg/us-east-1/k8s-kops/2-kops/Makefile
  apps-devstg/us-east-1/k8s-kops/2-kops/cluster-config.sh
  apps-devstg/us-east-1/k8s-kops/2-kops/cluster-template.sh
  apps-devstg/us-east-1/k8s-kops/2-kops/cluster-template.yml
  apps-devstg/us-east-1/k8s-kops/2-kops/cluster-update.sh
  apps-devstg/us-east-1/k8s-kops/2-kops/config.tf
  apps-devstg/us-east-1/k8s-kops/2-kops/values.yaml
  apps-devstg/us-east-1/k8s-kops/3-extras/README.md
  apps-devstg/us-east-1/k8s-kops/3-extras/chart-values/externaldns.yaml
  apps-devstg/us-east-1/k8s-kops/3-extras/chart-values/traefik.yaml
  apps-devstg/us-east-1/k8s-kops/3-extras/common-variables.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/config.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/external-dns.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/locals.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/route53record.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/terraform.auto.tfvars
  apps-devstg/us-east-1/k8s-kops/3-extras/traefik.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/variables.tf
  apps-devstg/us-east-1/k8s-kops/README.md
  apps-devstg/us-east-1/k8s-kops/TODO.md
Labels: enhancement, patch

#602 Feature | add and remove users
  management/global/sso/locals.tf
Labels: security, patch

#603 Doc | Adding apps-devstg genai llm rag chatbot with bedtock architecture diagram
  @doc/figures/genai-llm-rag-bedrock-poc.png
  README.md
  data-science/us-east-1/genai-llm-rag-bedrock-poc /README.md
Labels: patch, documentation

#604 Create an example Step Functions workflow that integrates with API Ga…
  data-science/us-east-1/workflow-order-processing/README.md
  data-science/us-east-1/workflow-order-processing/apigw.tf
  data-science/us-east-1/workflow-order-processing/common-variables.tf
  data-science/us-east-1/workflow-order-processing/config.tf
  data-science/us-east-1/workflow-order-processing/databases.tf
  data-science/us-east-1/workflow-order-processing/functions.tf
  data-science/us-east-1/workflow-order-processing/identities.tf
  data-science/us-east-1/workflow-order-processing/locals.tf
  data-science/us-east-1/workflow-order-processing/src/external_callback_handler/external_callback_handler.py
  data-science/us-east-1/workflow-order-processing/src/get_order_metadata_handler/get_order_metadata_handler.py
  data-science/us-east-1/workflow-order-processing/src/process_shipping_result_handler/process_shipping_result_handler.py
  data-science/us-east-1/workflow-order-processing/src/sns_callback_handler/sns_callback_handler.py
  data-science/us-east-1/workflow-order-processing/topics.tf
  data-science/us-east-1/workflow-order-processing/utils/run.py
  data-science/us-east-1/workflow-order-processing/variables.tf
  data-science/us-east-1/workflow-order-processing/workflows.tf
  management/global/sso/policies.tf
Labels: feature, minor

#606 Feature | add new devops user
  .github/release-drafter.yml
  config/common-variables.tf
  config/common.tfvars.example
  management/global/sso/.terraform.lock.hcl
  management/global/sso/locals.tf
Labels: security, patch
