Repository binbashar/le-tf-infra-aws, pull requests merged in 2024-06, with the labels that each got.

#573 Feature | Add AWS Security Hub configuration layer
  management/global/sso/policies.tf
  management/us-east-1/security-hub --/README.md
  management/us-east-1/security-hub --/common-variables.tf
  management/us-east-1/security-hub --/config.tf
  management/us-east-1/security-hub --/security_hub.tf
  security/us-east-1/security-hub --/README.md
  security/us-east-1/security-hub --/common-variables.tf
  security/us-east-1/security-hub --/config.tf
  security/us-east-1/security-hub --/security_hub.tf
Labels: feature

#572 ENHANCEMENT/ improved doc
  shared/us-east-1/tools-costs-notifications/README.md
Labels: enhancement, patch

#577 Feature | Reference ECS implementation
  apps-devstg/us-east-1/base-network/.terraform.lock.hcl
  apps-devstg/us-east-1/base-network/locals.tf
  apps-devstg/us-east-1/base-network/network.auto.tfvars
  apps-devstg/us-east-1/base-network/network.tf
  apps-devstg/us-east-1/ecs-demoapps/alb.tf
  apps-devstg/us-east-1/ecs-demoapps/common-variables.tf
  apps-devstg/us-east-1/ecs-demoapps/config.tf
  apps-devstg/us-east-1/ecs-demoapps/ecs.tf
  apps-devstg/us-east-1/ecs-demoapps/locals.tf
  apps-devstg/us-east-1/security-certs/.terraform.lock.hcl
  apps-devstg/us-east-1/security-certs/binbash.com.ar.tf
  apps-devstg/us-east-1/security-certs/config.tf
  build.env
  shared/global/base-dns/binbash.com.ar/zone_private.aws.binbash.com.ar.tf
Labels: feature, minor

#579 Remove unnecessary tfvars in DemoApps network layer
  apps-devstg/us-east-1/k8s-eks-demoapps/network/terraform.auto.tfvars
  apps-devstg/us-east-1/k8s-eks-demoapps/network/terraform.tfvars
Labels: patch, fix

#578 Unpin patches version restriction
  apps-devstg/global/base-identities/config.tf
  apps-prd/global/base-identities/config.tf
  management/global/base-identities/config.tf
  network/global/base-identities/config.tf
  security/global/base-identities/config.tf
  shared/global/base-identities/config.tf
  shared/us-east-1/container-registry/config.tf
  shared/us-east-1/tools-costs-notifications/config.tf
  shared/us-east-2/container-registry/config.tf
Labels: patch, fix

#592 Fix ECS service and add small documentation
  apps-devstg/us-east-1/ecs-demoapps/NOTES.md
  apps-devstg/us-east-1/ecs-demoapps/alb.tf
  apps-devstg/us-east-1/ecs-demoapps/locals.tf
Labels: minor, fix

#581 Add AWS secret retrieval for ArgoCD
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/cicd-argo.tf
Labels: feature, patch
