Repository binbashar/le-tf-infra-aws, pull requests merged in 2024-05, with the labels that each got.

#568 Feature/add new devops user
  management/global/sso/locals.tf
  management/global/sso/policies.tf
Labels: security, patch

#569 Create TF backend layer in the Data Science account
  data-science/us-east-1/base-tf-backend/README.md
  data-science/us-east-1/base-tf-backend/common-variables.tf
  data-science/us-east-1/base-tf-backend/config.tf
  data-science/us-east-1/base-tf-backend/locals.tf
  data-science/us-east-1/base-tf-backend/main.tf
  data-science/us-east-1/base-tf-backend/variables.tf
  management/global/sso/policies.tf
Labels: feature, patch

#570 Fix | shared vpn-server data source missing index
  shared/us-east-1/tools-vpn-server/ec2.tf
Labels: patch, fix

#574 Remove null resource to delegate config to Security Account
  management/global/organizations/locals.tf
  management/global/organizations/organization.tf
  management/us-east-1/security-compliance/awsconfig_delegation.tf
Labels: enhancement, patch
