Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-02, with the labels that each got.

#692 Fix | readme links
  README.md
Labels: patch, documentation

#705 Feature | Add new users to the datascientists group
  management/global/sso/locals.tf
  management/global/sso/policies.tf
Labels: patch

#704 Feature/lakehouse
  @doc/figures/binbash-lakehouse.png
  data-science/us-east-1/datalake-demo--/README.md
  data-science/us-east-1/datalake-demo--/athena.tf
  data-science/us-east-1/datalake-demo--/dms.tf
  data-science/us-east-1/datalake-demo--/etl.tf
  data-science/us-east-1/datalake-demo--/locals.tf
  data-science/us-east-1/datalake-demo--/outputs.tf
  data-science/us-east-1/datalake-demo--/s3.tf
  data-science/us-east-1/lakehouse-demo--/README.md
  data-science/us-east-1/lakehouse-demo--/common-variables.tf
  data-science/us-east-1/lakehouse-demo--/config.tf
  data-science/us-east-1/lakehouse-demo--/locals.tf
  data-science/us-east-1/lakehouse-demo--/redshift.tf
  management/global/sso/policies.tf
Labels: feature, patch

#703 Enhancement | Migrate test-static-code-and-linting from circleci to GithubActions
  .github/workflows/infracost.yml
  .github/workflows/leverage-cli-test.yml
  .github/workflows/test-static-code-and-linting.yml
Labels: feature, patch

#716 Feature | Add user leandro.mana to SSO with datascientists group
  .circleci/config.yml
  apps-prd/global/base-identities/roles.tf
  data-science/global/base-identities/roles.tf
  data-science/us-east-1/datalake-demo--/README.md
  data-science/us-east-1/datalake-demo--/etl.tf
  data-science/us-east-1/lakehouse-demo--/locals.tf
  data-science/us-east-1/lakehouse-demo--/redshift.tf
  management/global/base-identities/roles.tf
  management/global/sso/locals.tf
  network/global/base-identities/roles.tf
  security/global/base-identities/roles.tf
  shared/global/base-identities/roles.tf
Labels: security, patch

#721 Feature | Add default tagging for security keys layer
  .github/workflows/security-keys.yml
  apps-devstg/us-east-1/security-keys/config.tf
  apps-devstg/us-east-1/security-keys/kms.tf
  apps-devstg/us-east-1/security-keys/tests/kms.tftest.hcl
  apps-devstg/us-east-2/security-keys/config.tf
  apps-devstg/us-east-2/security-keys/kms.tf
  apps-prd/us-east-1/security-keys/config.tf
  apps-prd/us-east-1/security-keys/kms.tf
  data-science/us-east-1/security-keys/config.tf
  data-science/us-east-1/security-keys/kms.tf
  management/us-east-1/security-keys/config.tf
  management/us-east-1/security-keys/kms.tf
  network/us-east-1/security-keys/config.tf
  network/us-east-1/security-keys/kms.tf
  network/us-east-2/security-keys/config.tf
  network/us-east-2/security-keys/kms.tf
  security/us-east-1/security-keys/config.tf
  security/us-east-1/security-keys/kms.tf
  shared/us-east-1/security-keys/config.tf
  shared/us-east-1/security-keys/kms.tf
  shared/us-east-2/security-keys/config.tf
  shared/us-east-2/security-keys/kms.tf
Labels: enhancement, feature, patch
