Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-03, with the labels that each got.

#737 Update DevOps permissionset policy
  management/global/sso/policies.tf
Labels: patch, fix

#738 Enhacement | Add Workaround description for ECS Demo App with GLIBC compatibility issue
  apps-devstg/us-east-1/ecs-demoapps/README.md
Labels: bug, patch, documentation

#727 Enhacement | Update container registry layer to use a newer module
  shared/us-east-1/container-registry/.terraform.lock.hcl
  shared/us-east-1/container-registry/account.tf
  shared/us-east-1/container-registry/config.tf
  shared/us-east-1/container-registry/ecr_repositories.tf
  shared/us-east-1/container-registry/lifecycle_policy.tf
  shared/us-east-1/container-registry/locals.tf
  shared/us-east-1/container-registry/variables.tf
Labels: minor
