Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-07, with the labels that each got.

#854 Feature | Adding digger initial workflows
  .github/workflows/digger-dev-iam-keys.yml
  .github/workflows/digger-dev-iam-roles.yml
  .github/workflows/security-keys.yml
  .github/workflows/testing-workflow.yml
  shared/global/base-dns/binbash.com.ar/.terraform.lock.hcl
Labels: feature, patch

#857 removing digger related files
  .github/workflows/digger-dev-iam-keys.yml
  .github/workflows/digger-dev-iam-roles.yml
  digger.yml
  shared/global/base-identities/users.tf
  shared/global/base-identities/variables.tf
Labels: patch, fix

#866 Create DeployMaster role in data-science and some minor fixes
  management/global/base-identities/groups_policies.tf
  management/global/base-identities/keys/angelo.fenoglio
  management/global/base-identities/keys/diego.ojeda
  management/global/base-identities/keys/emiliano.brest
  management/global/base-identities/keys/exequiel.barrirero
  management/global/base-identities/keys/franco.gauchat
  management/global/base-identities/keys/jose.peinado
  management/global/base-identities/keys/luis.gallardo
  management/global/base-identities/keys/marcelo.beresvil
  management/global/base-identities/keys/marcos.pagnucco
  management/global/base-identities/keys/matias.rodriguez
  management/global/base-identities/role_policies.tf
  management/global/base-identities/roles.tf
  management/global/base-identities/variables.tf
  security/global/base-identities/.terraform.lock.hcl
  security/global/base-identities/groups_policies.tf
  security/global/base-identities/roles.tf
  security/global/base-identities/variables.tf
Labels: enhancement, minor, fix

#871 Remove unnecessary tag
  security/us-east-1/security-base/locals.tf
Labels: patch, fix

#875 Fix | Route53 www.binbash.com.ar to www.binbash.co redirect
  shared/global/base-dns/binbash.com.ar/zone_private.aws.binbash.com.ar.tf
  shared/global/base-dns/binbash.com.ar/zone_public.binbash.com.ar.tf
Labels: patch, fix
