Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-09, with the labels that each got.

#907 fix(k8s): disable PSP in cluster-autoscaler for EKS 1.31 compatibility
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/cluster-autoscaler.yaml
Labels: fix, dependencies, kubernetes

#946 Update Infracost workflow to ignore draft PRs again
  .github/workflows/infracost.yml
Labels: enhancement, fix

#956 Feat | Add new user 'hernan.rezilo' with devops group membership
  management/global/sso/locals.tf
Labels: enhancement, security, patch
