Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-01, with the labels that each got.

#684 Feature | AWS Client VPN
  management/global/sso/.terraform.lock.hcl
  management/global/sso/client-vpn-application.tf
  management/global/sso/config.tf
  management/global/sso/locals.tf
  network/us-east-1/client-vpn/.gitignore
  network/us-east-1/client-vpn/README.md
  network/us-east-1/client-vpn/client-vpn.tf
  network/us-east-1/client-vpn/common-variables.tf
  network/us-east-1/client-vpn/config.tf
  network/us-east-1/client-vpn/locals.tf
  network/us-east-1/client-vpn/outputs.tf
  network/us-east-1/client-vpn/sso-groups.tf
  network/us-east-1/security-certs/binbash.com.ar.tf
  network/us-east-1/security-certs/common-variables.tf
  network/us-east-1/security-certs/config.tf
  network/us-east-1/security-certs/locals.tf
  network/us-east-1/security-certs/outputs.tf
  network/us-east-1/security-certs/variables.tf
Labels: feature, patch

#687 Feature/sftp
  shared/us-east-1/storage/object-file-shares-sftp-transfer-service --/.terraform.lock.hcl
  shared/us-east-1/storage/object-file-shares-sftp-transfer-service --/config.tf
  shared/us-east-1/storage/object-file-shares-sftp-transfer-service --/s3.tf
  shared/us-east-1/storage/object-file-shares-sftp-transfer-service --/transfer-servers.tf
  shared/us-east-1/storage/object-file-shares-sftp-transfer-service --/transfer-users.tf
  shared/us-east-1/storage/object-file-shares-sftp-transfer-service --/variables.tf
Labels: enhancement, feature, patch

#659 Feature | Merge EKS clusters into one
  apps-devstg/us-east-1/k8s-eks-demoapps/README.md
  apps-devstg/us-east-1/k8s-eks-demoapps/cluster/eks-workers-managed.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/ids_fluentbit.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/ids_grafana.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/identities/outputs.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/argo-cd.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/argo-rollouts.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/argocd-image-updater.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/fluentbit.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/gatus.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/goldilocks.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/kube-prometheus-stack.yaml
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/cicd-argo.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/common-variables.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/config.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/identity-external-prometheus.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/identity-grafana-kubegraf.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/locals.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/monitoring-alerts.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/monitoring-cost.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/monitoring-logging.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/monitoring-metrics.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/monitoring-other.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/namespaces.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/networking-dns.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/networking-ingress.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/scaling.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/security.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/terraform.tfvars
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/variables.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/config.tf
  apps-devstg/us-east-1/k8s-eks/k8s-components/chart-values/kube-prometheus-stack.yaml
  build.env
  shared/us-east-1/secrets-manager/secrets.tf
Labels: enhancement, minor

#694 Fix/circile ci pre commit step
  .pre-commit-config.yaml
  apps-devstg/global/base-identities/policies.tf
  apps-devstg/us-east-1/databases-aurora-pgsql --/cluster_aurora.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/chart-values/argo-cd.yaml
  apps-devstg/us-east-1/k8s-kind/k8s-resources/config.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/locals.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/outputs.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/s3.tf
  apps-devstg/us-east-1/k8s-kops/1-prerequisites/terraform.auto.tfvars
  apps-devstg/us-east-1/k8s-kops/3-extras/config.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/route53record.tf
  apps-devstg/us-east-1/k8s-kops/3-extras/traefik.tf
  apps-devstg/us-east-1/k8s-kops/README.md
  apps-prd/global/base-identities/policies.tf
  data-science/us-east-1/base-network/config.tf
  data-science/us-east-1/base-network/locals.tf
  data-science/us-east-1/databases-aurora-mysql--/cluster_demoapps.tf
  data-science/us-east-1/databases-aurora-mysql--/config.tf
  data-science/us-east-1/databases-aurora-mysql--/database_resources.tf
  data-science/us-east-1/datalake-demo--/README.md
  data-science/us-east-1/datalake-demo--/config/table_mappings.json
  data-science/us-east-1/datalake-demo--/config/task_settings.json
  data-science/us-east-1/genai-llm-rag-bedrock-poc/README.md
  data-science/us-east-1/security-certs/binbash.co.tf
  data-science/us-east-1/workflow-order-processing/databases.tf
  data-science/us-east-1/workflow-order-processing/functions.tf
  data-science/us-east-1/workflow-order-processing/identities.tf
  data-science/us-east-1/workflow-order-processing/src/sns_callback_handler/sns_callback_handler.py
  data-science/us-east-1/workflow-order-processing/workflows.tf
  management/global/base-identities/policies.tf
  management/global/sso/locals.tf
  network/us-east-1/client-vpn/README.md
  network/us-east-1/client-vpn/client-vpn.tf
  network/us-east-1/client-vpn/config.tf
  network/us-east-1/client-vpn/locals.tf
  network/us-east-1/security-certs/binbash.com.ar.tf
  security/us-east-1/firewall-manager/fms.tf
  security/us-east-1/security-audit/cloudtrail.tf
  shared/global/base-identities/roles.tf
  shared/us-east-1/base-network/locals.tf
  shared/us-east-1/base-tf-backend/main.tf
  shared/us-east-1/tools-vpn-server/config.tf
  shared/us-east-1/tools-vpn-server/ec2.tf
Labels: patch, fix
