Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-08, with the labels that each got.

#884 Feat(sso) | Offboarding: Remove user entry from aws accounts
  management/global/sso/locals.tf
Labels: security, patch

#910 fix: add global schedule to renovate configuration
  renovate.json
Labels: bug, enhancement, dependencies

#888 feat: add Claude Code agents and bb-tackle command integration
  .claude/agents/cost-optimization.md
  .claude/agents/dependency-update.md
  .claude/agents/documentation.md
  .claude/agents/feature-implementation.md
  .claude/agents/issue-fix.md
  .claude/agents/security-compliance.md
  .claude/agents/terraform-layer.md
  .claude/commands/gh-issue-chore-deps.md
Labels: feature, patch, ai

#911 feat: remove vault agent injector from k8s-kind security resources
  apps-devstg/us-east-1/k8s-kind --/k8s-resources/security.tf
Labels: security, minor, cleanup

#889 feat(bedrock): Add KYB Data Automation infrastructure for business document processing
  data-science/us-east-1/bedrock-kyb-bda/.terraform.lock.hcl
  data-science/us-east-1/bedrock-kyb-bda/README.md
  data-science/us-east-1/bedrock-kyb-bda/bedrock.tf
  data-science/us-east-1/bedrock-kyb-bda/common-variables.tf
  data-science/us-east-1/bedrock-kyb-bda/config.tf
  data-science/us-east-1/bedrock-kyb-bda/eventbridge.tf
  data-science/us-east-1/bedrock-kyb-bda/iam.tf
  data-science/us-east-1/bedrock-kyb-bda/lambda.tf
  data-science/us-east-1/bedrock-kyb-bda/locals.tf
  data-science/us-east-1/bedrock-kyb-bda/outputs.tf
  data-science/us-east-1/bedrock-kyb-bda/s3.tf
  data-science/us-east-1/bedrock-kyb-bda/src/kyb-bda-processor/lambda_function.py
  data-science/us-east-1/bedrock-kyb-bda/variables.tf
Labels: feature, patch, ai

#915 feat: implement S3 lifecycle configurations for cost optimization
  .cursor/rules/core-rules.mdc
  apps-devstg/us-east-1/k8s-kops --/1-prerequisites/s3.tf
  management/global/cost-mgmt/.terraform.lock.hcl
  management/global/cost-mgmt/main.tf
  security/us-east-2/security-audit/awscloudtrail_replication.tf
  security/us-east-2/security-compliance --/awsconfig_replication.tf
Labels: enhancement, patch, cost-optimization

#914 feat: add metadata to Claude Code agent definitions
  .claude/agents/cost-optimization.md
  .claude/agents/dependency-update.md
  .claude/agents/documentation.md
  .claude/agents/feature-implementation.md
  .claude/agents/issue-fix.md
  .claude/agents/security-compliance.md
  .claude/agents/terraform-layer.md
Labels: patch, fix

#917 fix: update all var.accounts.root references to var.accounts.management
  apps-devstg/global/base-identities/roles.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/secrets/secrets.tf
  apps-devstg/us-east-1/secrets-manager/secrets.tf
  management/config/account.tfvars
  management/config/backend.tfvars
  management/us-east-1/notifications/costs_tools_monitoring.tf
  management/us-east-1/notifications/policies.tf
  management/us-east-1/security-keys/kms.tf
  network/global/base-identities/roles.tf
  security/us-east-1/security-compliance --/awsconfig.tf
  security/us-east-2/security-monitoring --/guardduty.tf
  shared/us-east-1/tools-costs-email-notifications/iam.tf
Labels: bug, patch, technical-debt

#918 Chore | Add Luis Gallardo to Administrators group
  management/global/sso/locals.tf
Labels: patch

#921 fix: convert AWS account IDs to strings
  config/common.tfvars.example
Labels: patch, fix

#880 Feature | Atlantis OpenTofu GitOps Automation ECS deployment
  .gitignore
  apps-devstg/global/base-identities/.terraform.lock.hcl
  apps-devstg/global/base-identities/roles.tf
  apps-devstg/us-east-1/k8s-eks-demoapps/network/terraform.tfvars
  apps-prd/global/base-identities/roles.tf
  config/common-variables.tf
  config/common.tfvars.example
  data-science/global/base-identities/roles.tf
  management/global/base-identities/role_policies.tf
  management/global/base-identities/roles.tf
  network/global/base-identities/roles.tf
  security/global/base-identities/groups.tf
  security/global/base-identities/groups_policies.tf
  security/global/base-identities/keys/machine.infra
  security/global/base-identities/locals.tf
  security/global/base-identities/outputs.tf
  security/global/base-identities/roles.tf
  security/global/base-identities/users.tf
  shared/global/base-identities/roles.tf
  shared/us-east-1/secrets-manager/locals.tf
  shared/us-east-1/secrets-manager/secrets.tf
  shared/us-east-1/security-keys/kms.tf
  shared/us-east-1/tools-atlantis-ecs/.terraform.lock.hcl
  shared/us-east-1/tools-atlantis-ecs/README.md
  shared/us-east-1/tools-atlantis-ecs/common-variables.tf
  shared/us-east-1/tools-atlantis-ecs/config.tf
  shared/us-east-1/tools-atlantis-ecs/locals.tf
  shared/us-east-1/tools-atlantis-ecs/main.tf
  shared/us-east-1/tools-atlantis-ecs/server-atlantis.yaml
  shared/us-east-1/tools-atlantis-ecs/variables.tf
Labels: feature, major
