Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-06, with the labels that each got.

#831 Enhancement | Terraform to Tofu migration in build.env + Data scientist permission set and marketplace seller
  build.env
  management/global/sso/.terraform.lock.hcl
  management/global/sso/locals.tf
  management/global/sso/policies.tf
Labels: enhancement, patch

#840 Enhancement | Migrate data-science account layers to OpenTofu
  data-science/global/base-identities/common-variables.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/README.md
  data-science/us-east-1/genai-llm-rag-bedrock-full--/alb.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/assets/images/genai-llm-rag-bedrock-full.png
  data-science/us-east-1/genai-llm-rag-bedrock-full--/common-variables.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/config.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/dns.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/ecr.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/ecs.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/github_workflow.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/iam.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/locals.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/opensearch.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full--/secret.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/README.md
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/alb.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/assets/images/genai-llm-rag-bedrock-poc.png
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/common-variables.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/config.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/dns.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/ecr.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/ecs.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/github_workflow.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/locals.tf
  data-science/us-east-1/genai-llm-rag-bedrock-poc--/secret.tf
  data-science/us-east-1/workflow-order-processing--/README.md
  data-science/us-east-1/workflow-order-processing--/apigw.tf
  data-science/us-east-1/workflow-order-processing--/common-variables.tf
  data-science/us-east-1/workflow-order-processing--/config.tf
  data-science/us-east-1/workflow-order-processing--/databases.tf
  data-science/us-east-1/workflow-order-processing--/functions.tf
  data-science/us-east-1/workflow-order-processing--/identities.tf
  data-science/us-east-1/workflow-order-processing--/locals.tf
  data-science/us-east-1/workflow-order-processing--/src/external_callback_handler/external_callback_handler.py
  data-science/us-east-1/workflow-order-processing--/src/get_order_metadata_handler/get_order_metadata_handler.py
  data-science/us-east-1/workflow-order-processing--/src/process_shipping_result_handler/process_shipping_result_handler.py
  data-science/us-east-1/workflow-order-processing--/src/sns_callback_handler/sns_callback_handler.py
  data-science/us-east-1/workflow-order-processing--/topics.tf
  data-science/us-east-1/workflow-order-processing--/utils/run.py
  data-science/us-east-1/workflow-order-processing--/variables.tf
  data-science/us-east-1/workflow-order-processing--/workflows.tf
Labels: enhancement, minor, opentofu

#849 Remove DevStg EKS VPC Peerings which are no longer necessary
  apps-devstg/us-east-1/base-network/.terraform.lock.hcl
  apps-devstg/us-east-1/base-network/build.env
  apps-devstg/us-east-1/base-network/config.tf
  apps-devstg/us-east-1/base-network/locals.tf
  apps-devstg/us-east-1/base-network/network.auto.tfvars
  data-science/us-east-1/base-network/locals.tf
  shared/us-east-1/base-network/locals.tf
Labels: minor, fix
