Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-05, with the labels that each got.

#805 Fix | Remove Firewall Manager and Network Firewall Resources
  apps-devstg/us-east-1/security-firewall --/.terraform.lock.hcl
  network/us-east-1/network-firewall --/README.md
  network/us-east-1/network-firewall --/common-variables.tf
  network/us-east-1/network-firewall --/config.tf
  network/us-east-1/network-firewall --/firewall.tf
  network/us-east-1/network-firewall --/locals.tf
  network/us-east-1/network-firewall --/network.tf
  network/us-east-1/network-firewall --/outputs.tf
  network/us-east-1/network-firewall --/variables.tf
  network/us-east-2/network-firewall --/README.md
  network/us-east-2/network-firewall --/common-variables.tf
  network/us-east-2/network-firewall --/config.tf
  network/us-east-2/network-firewall --/firewall.tf
  network/us-east-2/network-firewall --/locals.tf
  network/us-east-2/network-firewall --/network.tf
  network/us-east-2/network-firewall --/outputs.tf
  network/us-east-2/network-firewall --/variables.tf
  security/us-east-1/firewall-manager --/common-variables.tf
  security/us-east-1/firewall-manager --/config.tf
  security/us-east-1/firewall-manager --/dns_rules.tf
  security/us-east-1/firewall-manager --/fms.tf
  security/us-east-1/firewall-manager --/locals.tf
  security/us-east-1/firewall-manager --/nfw_rules.tf
  security/us-east-1/firewall-manager --/variables.tf
Labels: fix, cost-optimization

#806 Rename the management account from root to management
  config/common.tfvars.example
  management/global/organizations/accounts.tf
  management/global/organizations/locals.tf
  management/global/sso/account_assignments.tf
Labels: enhancement, patch

#811 Feature | Initialising cursor core, leverage doc, and terraform rules
  .cursor/rules/core-rules.mdc
  .cursor/rules/core-terraform-rules.mdc
  .cursor/rules/doc-leverage.mdc
  apps-devstg/us-east-1/storage/s3-bucket-demo-files --/bucket_demo_files.tf
  shared/us-east-1/storage/object-file-shares-for-users-list --/buckets.tf
Labels: feature, patch

#817 Feature | Add GenAI Workshop OU and Accounts, SSO Permission Set Assignments, and Documentation Updates
  management/global/organizations/.terraform.lock.hcl
  management/global/organizations/README.md
  management/global/organizations/locals.tf
  management/global/sso/account_assignments.tf
  management/global/sso/locals.tf
  management/global/sso/policies.tf
Labels: feature, patch

#812 FIX | Migration from vault to secrets manager
  apps-devstg/us-east-1/databases-aurora/.terraform.lock.hcl
  apps-devstg/us-east-1/databases-aurora/cluster_demoapps.tf
  apps-devstg/us-east-1/databases-aurora/config.tf
  apps-devstg/us-east-1/databases-mysql --/build.env
  apps-devstg/us-east-1/databases-mysql --/config.tf
  apps-devstg/us-east-1/databases-mysql --/db_mysql.tf
  management/us-east-1/notifications/config.tf
  management/us-east-1/notifications/costs_tools_monitoring.tf
  management/us-east-1/notifications/slack_tools_monitoring.tf
  management/us-east-1/notifications/slack_tools_monitoring_sec.tf
  network/us-east-1/notifications/config.tf
  network/us-east-1/notifications/slack_tools_monitoring.tf
  network/us-east-1/notifications/slack_tools_monitoring_sec.tf
  shared/us-east-1/notifications/config.tf
  shared/us-east-1/notifications/slack_tools_monitoring.tf
  shared/us-east-1/notifications/slack_tools_monitoring_sec.tf
  shared/us-east-1/secrets-manager/secrets.tf
Labels: minor, fix
