Repository binbashar/le-tf-infra-aws, pull requests merged in 2025-04, with the labels that each got.

#718 Add S3 bucket for ALB logs integation with EKS
  apps-devstg/us-east-1/alb-logs-s3-bucket/bucket.tf
  apps-devstg/us-east-1/alb-logs-s3-bucket/common-variables.tf
  apps-devstg/us-east-1/alb-logs-s3-bucket/config.tf
  apps-devstg/us-east-1/alb-logs-s3-bucket/locals.tf
  apps-devstg/us-east-1/alb-logs-s3-bucket/output.tf
Labels: feature, patch

#781 Fix | IAM policy for devops role with new actions and Inspector administration permissions
  management/global/sso/policies.tf
Labels: patch, fix

#774 720 genai full
  data-science/us-east-1/genai-llm-rag-bedrock-full/README.md
  data-science/us-east-1/genai-llm-rag-bedrock-full/alb.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/assets/images/genai-llm-rag-bedrock-full.png
  data-science/us-east-1/genai-llm-rag-bedrock-full/common-variables.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/config.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/dns.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/ecr.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/ecs.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/github_workflow.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/iam.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/locals.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/opensearch.tf
  data-science/us-east-1/genai-llm-rag-bedrock-full/secret.tf
  management/global/sso/policies.tf
Labels: feature, patch

#794 #793 Increase sso session duration for datascientists
  management/global/sso/.terraform.lock.hcl
  management/global/sso/permission_sets.tf
Labels: minor

#795 Add AWS Marketplace User Permissions to SSO Configuration
  management/global/sso/locals.tf
  management/global/sso/permission_sets.tf
Labels: enhancement, permissions, sso
